<?php

namespace AppBundle\Repository;

/**
 * repositoriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class repositoriesRepository extends \Doctrine\ORM\EntityRepository
{
}
